### PR TITLE
Upgrade Cake to 0.17.0

### PR DESCRIPTION
**Pull request by devlead**
Cake 0.18.0 will requires at least version 0.16.x to work.

### CODE REVIEW

**Comment by Symbianx** [comment]
@Redth  Any ETA on this to be merged? All my builds are failing because of this dependency.

**Comment by Redth** [comment]
Sorry but I'm on vacation with limited access. If someone can make this PR pass the build checks I can merge and publish.

**Review by Symbianx — CHANGES_REQUESTED** [review]
The CakeEnvironment constructor call in line 21 of FakeCakeContext.cs is missing the third parameter, ICakeLog. Adding a `new FakeLog()` call should fix the build.

**Comment by devlead** [comment]
@Redth I'll take a look the PR.

**Comment by devlead** [comment]
@Redth constructor issue fixed ✔️

**Review by Symbianx — APPROVED** [review]

**Comment by gep13** [comment]
@Redth @devlead I think this PR can be closed, as the work as already been done directly in the main branch.

**Comment by devlead** [comment]
Yes I'll close this PR.

**Pull request closed without merging**
